### ISSUE TITLE
滚动时如何可以设置点击事件

### ISSUE THREAD

**Issue by gitfornncn** [akindone/flutterMarquee#1]
我尝试在内容包括点击事件，可是当文本滚动的时候，是无法触发点击的，我想应该是滚动在执行。无法同时处理点击。想问下有什么思路能解决这个问题吗

**Comment by 370966584** [comment]
> 我尝试在内容包括点击事件，可是当文本滚动的时候，是无法触发点击的，我想应该是滚动在执行。无法同时处理点击。想问下有什么思路能解决这个问题吗

我也遇到这个问题了 请问你解决了吗
